---
- name: Docker Setup
  hosts: all
  tasks:
          - name: Install required packages
            apt:
                    pkg:
                            - apt-transport-https
                            - ca-certificates
                            - curl
                            - gnupg
                            - lsb-release
          
          - name: Add Docker GPG key
            ansible.builtin.apt_key:
                    url: https://download.docker.com/linux/ubuntu/gpg
                    state: present
            
          - name: Add Docker repository
            ansible.builtin.apt_repository:
                    repo: deb https://download.docker.com/linux/ubuntu bionic stable
                    state: present
            
          - name: Install Docker engine and Containerd
            apt:
                    pkg:
                            - docker-ce
                            - docker-ce-cli
                            - containerd.io
          
          - name: Enable Docker on startup
            ansible.builtin.service:
                    name: docker
                    enabled: yes
            
          - name: Start Docker, if not started
            ansible.builtin.service:
                    name: docker
                    state: started
            
          - name: Install Docker Compose
            get_url:
                    url: https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64
                    dest: /usr/local/bin/docker-compose
                    mode: 0755
